### PR TITLE
#276: Fix some grammar bugs

### LINKED ISSUE #276: Grammar bugs
- [ ] `new` is not a Swift keyword
- [ ] Variadic parameter types [eg: `Int...`] not in grammar
- [ ] `where` clause in `for in` loops parsed incorrectly

### PR DESCRIPTION
**Pull request by a4sriniv**
Fixes #276.

- Fix grammar issues
- Fix `BraceStyleListener` to accomodate for `where` clause in `for-in` loops

### CODE REVIEW

File: src/main/java/com/sleekbyte/tailor/listeners/BraceStyleListener.java [hunk 1]
```diff
@@ -160,7 +160,8 @@ private void verifySwitchStatementBraceStyle(SwiftParser.SwitchStatementContext
     }
 
     private void verifyForInStatementBraceStyle(SwiftParser.ForInStatementContext ctx) {
-        verifyCodeBlockOpenBraceStyle(ctx.codeBlock(), ctx.expression().getStop(), Messages.FOR_IN_LOOP);
+        Token leftOfCodeBlock = ctx.whereClause() == null ? ctx.expression().getStop() : ctx.whereClause().getStop();
+        verifyCodeBlockOpenBraceStyle(ctx.codeBlock(), leftOfCodeBlock, Messages.FOR_IN_LOOP);
```
Comment (adityatrivedi) [inline src/main/java/com/sleekbyte/tailor/listeners/BraceStyleListener.java]: Good catch!

**Comment by adityatrivedi** [comment]
:-1:

**Comment by alykhank** [comment]
:+1:
