### PR TITLE
#425: Fix expressionElement grammar issue

### LINKED ISSUE #425: File parse failure when selectors of valid form are used
As previously reported in #354 #360 and ostensibly fixed in #357 (incorporated into release v0.8.0).

Selectors of the form `#selector(mySelector(_:))` cause the file to fail to parse (while those of the form `#selector(mySelector)` succeed).

**Tailor Version:** 0.10.0
**Swift Version:** 2.2
**Platform (Mac/Linux/Windows/CI):** Mac
**Installation Method:** Homebrew

### Steps to Reproduce Issue

Make a new file `/tmp/test.swift`:
```swift
import Cocoa

extension MyTextField: NSTextFieldDelegate {

    func control(control: NSControl, textView: NSTextView, doCommandBySelector commandSelector: Selector) -> Bool {
        if commandSelector == #selector(insertTab(_:)) {
            control.currentEditor()?.complete(nil)
            return true
        }

        return false
    }

}
```

```
$ tailor tailor /tmp/test.swift
Analyzing 1 file:
S

********** /tmp/test.swift **********
test.swift could not be parsed successfully, skipping...

Analyzed 0 files, skipped 1 file, and detected 0 violations (0 errors, 0 warnings).
```

### Expected Behavior
Parses file

### Actual Behavior
Fails to parse file

### PR DESCRIPTION
**Pull request by a4sriniv**
Fixes #425.

### CODE REVIEW

File: src/main/java/com/sleekbyte/tailor/listeners/whitespace/ColonWhitespaceListener.java [hunk 1]
```diff
@@ -99,9 +99,13 @@ public void enterExpressionElement(SwiftParser.ExpressionElementContext ctx) {
         if (ctx.expressionElementIdentifier() != null) {
             Token colon = ((TerminalNodeImpl) ctx.getChild(1)).getSymbol();
             Token left = ctx.expressionElementIdentifier().getStop();
```
Comment (adityatrivedi) [inline src/main/java/com/sleekbyte/tailor/listeners/whitespace/ColonWhitespaceListener.java]: `left` token can go inside the `else` block

**Comment by adityatrivedi** [comment]
👍

**Comment by alykhank** [comment]
:+1:
