### PR TITLE
#209: Grammar fixes

### LINKED ISSUE #209: Grammar bugs
- [ ] Attributes can have punctuation (eg: `@objc(beforeEachWithMetadata:)`)
- [ ] Variables can be named `optional`

### PR DESCRIPTION
**Pull request by a4sriniv**
- Fixes #209
- Updated context sensitive keywords list

**Note**: The grammar for macros isn't well documented and it appears you can use more than just build configurations as macro conditionals. I'm assuming that any conditional clause can be put in there for the time being, until I find something more specific.

### CODE REVIEW

File: src/test/swift/com/sleekbyte/tailor/grammar/Macros.swift [hunk 1]
```diff
@@ -74,3 +74,11 @@ self.totalBytes = {
 #else
   let bytesPerPixel: CGFloat = 3.0
 #endif
+
+public var isRunningOnDevice: Bool = {
```
Comment (adityatrivedi) [inline src/test/swift/com/sleekbyte/tailor/grammar/Macros.swift]: Where do you find such stuff lol.

**Comment by adityatrivedi** [comment]
:+1: Great work!
